// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhaaogNBX7GQkg5ZV8oYcef8uSqFNYXg',
    appId: '1:752304031681:android:716ee372d53287270c9140',
    messagingSenderId: '752304031681',
    projectId: 'flutter-sem-iv',
    databaseURL: 'https://flutter-sem-iv-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sem-iv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKIcw7XJP9DwuvlQeEQul-ou849rY6bM',
    appId: '1:752304031681:ios:e0ad09c26453055e0c9140',
    messagingSenderId: '752304031681',
    projectId: 'flutter-sem-iv',
    databaseURL: 'https://flutter-sem-iv-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sem-iv.appspot.com',
    iosClientId: '752304031681-ecujq04osbu0o2f45fhelj9v8ucnm508.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceSystem',
  );
}
